### ISSUE TITLE
Directives for css-grid

### ISSUE THREAD

**Issue by niklas-wortmann** [opitzconsulting/ng-tools#8]
Quite similar to @angular/flex-layout we could provide useful directives for css-grid.

**Comment by stephanrauh** [comment]
Actually, there's already a great library doing just that: https://github.com/angular/flex-layout.

**Comment by niklas-wortmann** [comment]
Angular Flex Layout is a library providing directives for flexbox. Flexbox and css grid are both native implementations for layouting but slightly different, see https://tutorialzine.com/2017/03/css-grid-vs-flexbox

**Comment by stephanrauh** [comment]
OK, got it. This is one of the few opportunities to be the first. If I'm not mistaken, there's no Angular library supporting CSS grid yet. Let's hurry!
